#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
S1102 — THE PROBE «LADDER-ANCESTOR»: a shared ancestor of the d+1<=4 boundary + a WRITE FENCE.
Exante: active-v10.2/hub/prime/LADDER_ANCESTOR_EXANTE.md (a project ruling, S1101).
Seed:   active-v10.2/hub/prime/AUTHOR_SEED_quintic_solvability_d4_limit.md

Executor: an independent hand.  Order: A(probe) -> J-row B -> the project's verdict.  STOP for the visa.

THE KILL-TEST PRINCIPLE:
  * Galois/Abel-Ruffini = a REFERENCE (multiplicity 0).  The derived series, its steps, and
    solvability are counted BY OUR OWN HAND (an iterated commutant down to {e}), NOT by
    importing the theorem "S_n is solvable <=> n<=4" as an input.  Solvability is READ from
    the constructed series.
  * A new constant = STOP.  The fence is a binary group condition, with no threshold-handles.
  * Every detector is OBLIGED to be able to say NO (by a negative-world law).

Output: a class of 10/0/0 (pass/fail/skip) for every T, exit 0 only if every tooth moves
the right way (positives PASSED, negative-worlds FAILED, the S5 control REJECTED).
"""
from sympy.combinatorics import Permutation, PermutationGroup
from sympy.combinatorics.named_groups import SymmetricGroup, AlternatingGroup, CyclicGroup
from sympy import Poly, symbols, QQ
from sympy.polys.numberfields.galoisgroups import galois_group
import sys

x = symbols('x')

PASS, FAIL, SKIP = [], [], []
def ok(tag, msg):   PASS.append((tag, msg));  print(f"  [PASS] {tag}: {msg}")
def bad(tag, msg):  FAIL.append((tag, msg));  print(f"  [FAIL] {tag}: {msg}")
def skip(tag, msg): SKIP.append((tag, msg));  print(f"  [SKIP] {tag}: {msg}")

# ------------------------------------------------------------------ OUR OWN HAND
# The commutant is counted by a FULL enumeration of elements (the groups are small,
# |G|<=720): [G,H] = <[g,h] : g in ALL elements of G, h in ALL elements of H>.  This is a
# definition, not a theorem; we do NOT truncate to generators (truncation = a bug, caught
# by the tooth).
def commutator_subgroup(G, H):
    """[G,H] by full enumeration: the subgroup generated by all commutators [g,h]."""
    deg = G.degree
    gens = []
    for g in G.elements:
        for h in H.elements:
            c = g*h*g**-1*h**-1
            if not c.is_identity:
                gens.append(c)
    if not gens:
        return PermutationGroup([Permutation(list(range(deg)))])  # trivial
    return PermutationGroup(gens)

def derived_series_by_hand(G):
    """The derived series G >= G' >= G'' >= ... down to stabilization.  By our own hand (the commutant)."""
    series = [G]
    cur = G
    while True:
        nxt = commutator_subgroup(cur, cur)
        if nxt.order() == cur.order():
            break
        series.append(nxt)
        cur = nxt
        if cur.order() == 1:
            break
    return series

def lower_central_series_by_hand(G):
    """The lower central series: gamma_1=G, gamma_{k+1}=[G,gamma_k], down to stabilization."""
    series = [G]
    cur = G
    while True:
        nxt = commutator_subgroup(G, cur)
        if nxt.order() == cur.order():
            break
        series.append(nxt)
        cur = nxt
        if cur.order() == 1:
            break
    return series

def is_solvable_by_hand(G):
    """Solvability is READ: does the derived series reach {e}?  (a definition, not a theorem)"""
    return derived_series_by_hand(G)[-1].order() == 1

def terminal_abelian_step(G):
    """The last NONTRIVIAL step of the derived series IF the series reaches {e}; otherwise
    None (an unsolvable tail = there is no terminal abelian step)."""
    s = derived_series_by_hand(G)
    if s[-1].order() != 1:
        return None            # stuck on a nonabelian simple group (e.g. A5) -> none
    return s[-2] if len(s) >= 2 else s[-1]

def same_subgroup(A, B):
    """Equality of subgroups of Sym(axes) as SETS of permutations (the same action on the same axes)."""
    if A.order() != B.order():
        return False
    return A.is_subgroup(B) and B.is_subgroup(A)

# ------------------------------------------------------------------ DEMOCRACY
def democracy(n):
    """S_n on the n axes of the cell (0..n-1).  n = d+1."""
    return SymmetricGroup(n)

def full_cycle(n):
    """A full n-cycle = the Z/n clock, the canonical embedding (0 1 2 ... n-1)."""
    return Permutation([ (i+1) % n for i in range(n) ])   # i -> i+1 mod n

def cyclic_from(perm):
    return PermutationGroup([perm])

def galois_of(poly_expr):
    """The Galois group of an IRREDUCIBLE polynomial = the permutation group of its roots (a
    construction, not a theorem).  Returns a PermutationGroup or raises if reducible."""
    G, _ = galois_group(Poly(poly_expr, x))
    return G

# ============================================================ T3 — THE WRITE FENCE
def fence_number(poly_expr, name):
    """The fence for an ALGEBRAIC NUMBER given by its defining polynomial.
    Rule (binary, 0 handles): legal <=> the Galois group of the min-polynomial is
    SOLVABLE (the derived series is read down to {e} by our own hand).  If reducible => each
    irreducible factor is judged separately (the number = a root of one of them); legal <=>
    ALL factors are solvable.  Rational/linear => trivially legal (a named degeneration).
    Returns (legal: bool, detail: str)."""
    p = Poly(poly_expr, x, domain=QQ)
    factors = [fp for (fp, m) in p.factor_list()[1]]
    degs = sorted(fp.degree() for fp in factors)
    if all(fp.degree() == 1 for fp in factors):
        return True, f"rational/linear (degrees {degs}) — legal TRIVIALLY (a degeneration)"
    parts = []
    all_solv = True
    for fp in factors:
        if fp.degree() == 1:
            parts.append("lin:solv."); continue
        G = galois_of(fp.as_expr())
        solv = is_solvable_by_hand(G)
        all_solv = all_solv and solv
        parts.append(f"deg{fp.degree()}:|Gal|={G.order()},{'solv.' if solv else 'NOT SOLV.'}")
    return all_solv, "; ".join(parts) + (f"  (degrees of factors {degs})" if len(factors)>1 else "")

# ============================================== MEASURED CARRIERS (independent definitions)
def valley_Z3():
    """d=2: valley-ℤ₃ = R(111) = a lattice automorphism, a cyclic shift of 3 X-axes into ONE
    orbit (S359).  An independent definition of the mark's carrier: a 3-cycle of axes."""
    return PermutationGroup([Permutation([1, 2, 0])])   # (0 1 2)

def pairings_of_4():
    """3 pairings of {0,1,2,3} into two pairs: P0={01|23}, P1={02|13}, P2={03|12}."""
    return [
        frozenset([frozenset([0, 1]), frozenset([2, 3])]),
        frozenset([frozenset([0, 2]), frozenset([1, 3])]),
        frozenset([frozenset([0, 3]), frozenset([1, 2])]),
    ]

def induced_on_pairings(g):
    """The permutation induced by g on the 3 pairings (the action of Test-3: S₄ -> S₃)."""
    P = pairings_of_4()
    def act(pairing):
        return frozenset(frozenset(g(i) for i in pair) for pair in pairing)
    return tuple(P.index(act(p)) for p in P)

def test3_kernel():
    """d=3: the kernel of Test-3 = {g in S₄ : g fixes ALL 3 pairings} — an INDEPENDENT
    definition of the carrier (the medial/V₄ line), not "V₄ by name".  Must come out = the
    double transpositions."""
    S4 = SymmetricGroup(4)
    ker = [g for g in S4.elements if induced_on_pairings(g) == (0, 1, 2)]
    return PermutationGroup(ker)

# ============================================================ T1 — THE SEAM OF CARRIERS
def run_T1():
    print("\n=== T1 — THE SEAM OF CARRIERS (the action of the terminal step of the derived series of S_{d+1} = the mark's carrier) ===")

    # --- d=2: the terminal step S₃ =?= valley-ℤ₃ (an independent def.: a 3-shift of axes) ---
    S3 = democracy(3)
    T3step = terminal_abelian_step(S3)
    valley = valley_Z3()
    if same_subgroup(T3step, valley):
        ok("T1/d=2", f"the terminal step S₃ (|{T3step.order()}|) = valley-ℤ₃ as a SUBGROUP of "
                      f"axes (equivariantly: both = a cyclic ℤ/3-shift of 3 axes)")
    else:
        bad("T1/d=2", "the terminal step S₃ ≠ valley-ℤ₃")

    # --- d=3: the terminal step S₄ =?= the kernel of Test-3 (an independent def.: fixing all pairings) ---
    S4 = democracy(4)
    T4step = terminal_abelian_step(S4)
    ker3 = test3_kernel()
    # independence of the definition: ker3 is built by the action on pairings, NOT as "V₄"
    dts = sorted(str(g) for g in ker3.elements)
    if same_subgroup(T4step, ker3):
        ok("T1/d=3", f"the terminal step S₄ (|{T4step.order()}|) = the kernel of Test-3 (S₄→S₃ on "
                      f"pairings) as a SUBGROUP of axes — an equivariant equality, not a "
                      f"coincidence of names")
        # EQUIVARIANCE explicitly: ker3 acts TRIVIALLY on the 3 pairings, the complement does not
        acts_triv = all(induced_on_pairings(g) == (0, 1, 2) for g in ker3.elements)
        moves = [induced_on_pairings(g) for g in S4.elements if induced_on_pairings(g) != (0,1,2)]
        if acts_triv and len(set(moves)) == 5:  # S3\{e} = 5 nontrivial permutations
            ok("T1/d=3-eqv", "equivariance: the kernel acts trivially on the pairings, "
                              "the quotient S₄/V₄ = the full S₃ (5 nontrivial actions) — an "
                              "ACTION, not a name")
        else:
            bad("T1/d=3-eqv", "the equivariant structure of the pairings did not match")
    else:
        bad("T1/d=3", "the terminal step S₄ ≠ the kernel of Test-3")

    # ---------- NEGATIVE-WORLDS BY LAW (the detector is OBLIGED to say NO) ----------
    # (i-a) a different ladder of the same object: the lower central series S₄ -> A₄ (not V₄)
    lcs = lower_central_series_by_hand(S4)
    lcs_term = lcs[-1]
    if not same_subgroup(lcs_term, ker3):
        ok("T1-negworld(i)", f"the lower central series S₄ terminates at |{lcs_term.order()}| (A₄) ≠ "
                             f"the carrier V₄ — the detector said NO (a different ladder ⟹ "
                             f"the coincidence BROKE)")
    else:
        bad("T1-negworld(i)", "the lower central series coincided with the carrier — the detector CANNOT say NO")

    # (i-b) the middle step A₄ (not terminal) as a false candidate
    A4 = AlternatingGroup(4)
    if not same_subgroup(A4, ker3):
        ok("T1-negworld(i-b)", f"A₄ (|12|, a middle step) ≠ the carrier V₄ (|4|) — NO")
    else:
        bad("T1-negworld(i-b)", "A₄ coincided with the carrier")

    # (ii) broken democracy: S₃ instead of S₄ (the mark on 3 axes) -> the carrier DRIFTED AWAY
    T3_as_d3 = terminal_abelian_step(democracy(3))   # ℤ/3, order 3 ≠ V₄
    if T3_as_d3.order() != ker3.order():
        ok("T1-negworld(ii)", f"broken democracy S₃ terminates at |{T3_as_d3.order()}| (ℤ/3) ≠ the "
                              f"carrier for d=3 |{ker3.order()}| (V₄) — the carrier DRIFTED "
                              f"AWAY, the detector said NO")
    else:
        bad("T1-negworld(ii)", "S₃ gave the carrier for d=3 — the democracy-break was not caught")

# ============================================================ T2 — THE SEAM OF THE CLOCK
def sin_active(nu, h):
    """Hand-A (S1005/S1011): time-activity of ν ⟺ sin(2πν/h) ≠ 0 ⟺ ν ∉ {0, h/2}."""
    from sympy import sin, pi, Rational
    return sin(2*pi*Rational(nu, h)) != 0

def step_active(nu, h, clock, Tstep):
    """Hand-B (the step): does the character of ν read ⟨c⟩∩Tstep nontrivially?
    ν is nontrivial on the intersection ⟺ there exists g in (⟨c⟩∩Tstep) with
    e^{2πi ν k(g)/h} ≠ 1, where k(g) = the power of c that gives g.  Returns
    (active, |intersection|)."""
    from sympy import exp, I, pi, Rational, simplify
    c = clock.generators[0]
    # the elements of the intersection ⟨c⟩ ∩ Tstep, with their power k
    inter = []
    cur = Permutation(list(range(clock.degree)))
    for k in range(h):
        if k > 0:
            cur = cur * c
        if Tstep.contains(cur):
            inter.append(k)
    # ν is active ⟺ the character is nontrivial on some nonzero element of the intersection
    active = any(simplify(exp(2*I*pi*Rational(nu*k, h)) - 1) != 0 for k in inter if k != 0)
    return active, len(inter)

def run_T2():
    print("\n=== T2 — THE SEAM OF THE CLOCK (the sin-criterion ⊥ the step-criterion, by both hands) ===")
    for d in (2, 3):
        h = d + 1
        G = democracy(h)
        Tstep = terminal_abelian_step(G)
        clock = cyclic_from(full_cycle(h))          # canonical embedding = the full (d+1)-cycle
        # canonicity: the clock is the UNIQUE full cycle up to conjugation (the Coxeter class)
        if clock.order() == h:
            ok(f"T2/d={d}-canon", f"the clock = the full {h}-cycle ⟨c⟩, |{h}| (a Coxeter element) — a canonical embedding")
        else:
            bad(f"T2/d={d}-canon", "the clock is not of order h")
        agree = True
        active_sin, active_step = [], []
        for nu in range(h):
            a_sin = bool(sin_active(nu, h))
            a_step, inter_sz = step_active(nu, h, clock, Tstep)
            if a_sin: active_sin.append(nu)
            if a_step: active_step.append(nu)
            if a_sin != a_step:
                agree = False
                bad(f"T2/d={d}", f"ν={nu}: sin={a_sin} ≠ step={a_step} (the hands DIVERGED)")
        if agree:
            ok(f"T2/d={d}", f"BOTH hands agree: time-active ν={active_sin} "
                            f"(|⟨c⟩∩term|={inter_sz}); the sin-criterion = the step-criterion")

    # ---------- d=4 CONTROL-NEGWORLD: the clock sinks into A₅ (no terminal step) ----------
    S5 = democracy(5)
    Tstep5 = terminal_abelian_step(S5)
    if Tstep5 is None:
        ok("T2-boundary/d=4", "S₅: the derived series is stuck on A₅ (a nonabelian simple group) ⟹ "
                          "THERE IS NO TERMINAL ABELIAN STEP — the step-hand has NOTHING TO "
                          "READ (the clock sinks into A₅).  The sin-hand still turns "
                          "(ν∈{1,2,3,4}), but the seam FALLS APART = a fence of a boundary, "
                          "not a witness")
    else:
        bad("T2-boundary/d=4", "S₅ gave a terminal abelian step — the boundary was not caught")

    # ---------- NEGWORLD: the clock embedded NOT as a cycle (scattered) — the bridge MUST fall ----------
    # d=3: a forgery of ℤ/4 as ⟨(01)(23)⟩ (order 2, not a full 4-cycle) — does not realize the clock
    fake = PermutationGroup([Permutation([1, 0, 3, 2])])   # (01)(23), order 2
    if fake.order() != 4:
        ok("T2-negworld", f"the scattered clock ⟨(01)(23)⟩ = |{fake.order()}| ≠ 4 — does NOT realize "
                          f"ℤ/4, the bridge fell (the detector said NO to a non-cycle)")
    else:
        bad("T2-negworld", "the scattered clock produced ℤ/4 — the detector did not catch it")

def run_T3():
    print("\n=== T3 — THE WRITE FENCE (deliverable: «guards against false irrationals») ===")
    d = 3
    # (a) the model's registry numbers + the roots of the seed's gate — MUST pass (legal=True)
    registry = [
        ("Gram −1/d = −1/3",        x + 1),                    # rational (linear after *3): a degeneration
        ("v² = (d+1)²/(2d) = 8/3",  3*x - 8),                  # rational
        ("T(k) ∈ ℤ (e.g. 2)",       x - 2),                    # an integer
        ("the hexagon e^{±iπ/3}",    x**2 - x + 1),            # Φ_6, cyclotomic -> abelian
        ("the plastic ρ (x³−x−1)",   x**3 - x - 1),            # a cubic, S_3
        ("the golden φ (x²−x−1)",    x**2 - x - 1),            # quadratic, Z/2
        ("the 1/ρ-branch of the seed (x³+x²−1)", x**3 + x**2 - 1),         # a cubic, S_3
        ("the seed's §4 inverse slice x⁵+x−1 (a 2+3 factorization)", x**5 + x - 1),  # (x²−x+1)(x³+x²−1)
    ]
    for name, poly in registry:
        legal, detail = fence_number(poly, name)
        if legal:
            ok("T3-registry", f"{name}: PASSED the fence — {detail}")
        else:
            bad("T3-registry", f"{name}: FAILED (should have passed!) — {detail}")

    # (b) A TOOTH in both directions:
    #  the S5 control x⁵−x−1 MUST be REJECTED (legal=False)
    legal, detail = fence_number(x**5 - x - 1, "control x⁵−x−1")
    if not legal:
        ok("T3-tooth", f"the control x⁵−x−1 (Galois S₅): REJECTED by the fence — {detail}")
    else:
        bad("T3-tooth", f"the control x⁵−x−1 PASSED the fence — the tooth does NOT bite ({detail})")
    #  the degenerate control (rational) MUST pass TRIVIALLY (a named degeneration)
    legal, detail = fence_number(x - 1, "degenerate control x−1")
    if legal:
        ok("T3-tooth", f"the degenerate control x−1: TRUE trivially (a named degeneration) — {detail}")
    else:
        bad("T3-tooth", "the degenerate control x−1 FAILED — the fence is broken on a rational")
    #  a second unsolvable control (a different address, not a coincidence): x⁵−x+1 is also S₅
    legal, detail = fence_number(x**5 - x + 1, "control-2 x⁵−x+1")
    if not legal:
        ok("T3-tooth", f"control-2 x⁵−x+1 (Galois S₅): REJECTED — {detail}")
    else:
        bad("T3-tooth", f"control-2 x⁵−x+1 PASSED — {detail}")

# ==================================================================== MAIN
if __name__ == "__main__":
    print("S1102 — THE PROBE LADDER-ANCESTOR (exante S1101, project ruling).  Executor: an independent hand.")
    print("Solvability/steps = our own hand (the commutant by full enumeration); Galois = a reference.")
    run_T1()
    run_T2()
    run_T3()
    print(f"\n===== CLASS: {len(PASS)}/{len(FAIL)}/{len(SKIP)} (pass/fail/skip) =====")
    if FAIL:
        print("TEETH FAILED — report loudly (the front's norm):")
        for tag, msg in FAIL:
            print(f"  ! {tag}: {msg}")
        sys.exit(1)
    print("All teeth move the right way (positives passed, negative-worlds failed, S₅ rejected).")
    sys.exit(0)
