import Mathlib.Tactic

set_option linter.style.header false

/-!
# DIM: exact-rational / Layer-1 · T26.3 — COMMUTANT LADDER (block ranks)

WHAT IS PROVED HERE (snapshot d in {2,3}, interior 1 <= m <= d):
the decomposition of `V = {Sum x = 0} subset Q^(d+1)` under the Young subgroup
`Sym(m) x Sym(d+1-m)` into blocks of MEASURED dimensions `(1, m-1, d-m)`, term by term:
(a) every block vector lies in V (its coordinate sum is 0);
(b) the NON-EMPTY blocks are together LINEARLY INDEPENDENT and form a BASIS of V:
    d vectors (one coordinate dropped) have det != 0, hence rank d = dim V;
(c) the block DIMENSIONS are `(1, m-1, d-m)`, summing to d;
(d) the LADDER VALUES (number of non-empty blocks) are as listed in the erratum below.

ERRATUM TO LINE (d) — 2026-07-29. The line above is NOT rewritten; the qualifier
stands beside it. The sequences claimed there were shifted by one d relative to what
the THEOREM BODIES of this file actually prove:
  * proved: d=2 (m=1,2)   -> ladder 2/2     (`ladder21`, `ladder22`)
  * proved: d=3 (m=1,2,3) -> ladder 2/3/2   (`ladder31`, `ladder32`, `ladder33`)
  * the claim "2/3/2"   in fact corresponds to d=3, not d=2
  * the claim "2/3/3/2" corresponds to d=4 — NOT PROVED BY ANY THEOREM IN THIS FILE.
The theorem bodies are CLEAN (`by decide`, values correct); the defect was exactly in
the summary line of the header, i.e. in the one place of the file read by someone who
does not read Lean. Class: "machine-checked" is read as a guarantee over the WHOLE
file, while the machine checks only the bodies.

WHY THIS IS NOT A TAUTOLOGY: `1+(m-1)+(d-m)=d` as ARITHMETIC would be true by typing.
The content is (b): the blocks could have been DEPENDENT, or could have failed to span
V — det != 0 excludes that BY MEASUREMENT, not by postulate. A mutant of the ancestor
(swapping m-1 and d-m) is caught, because the block STRUCTURE differs, not merely the
sum of dimensions.

WHAT IS NOT PROVED AND NOT CLAIMED: that these subspaces are exactly the Sym ISOTYPES
(invariance under the whole Young subgroup). What is proved is the DIMENSIONAL
decomposition; the identification "block = isotype" is carried by the ANCESTOR
(S1000-T2, character count). The same split as in T34: the kernel here, the
interpretation in the ancestor. The words "time/clock/column" do not occur in any
statement.

SNAPSHOT d in {2,3}, NOT for all d, and the reason is TECHNICAL: dim V = d, while
Mathlib provides `det_fin_two/three` only up to 3x3. d=4 (4x4) is deliberately not
taken (a named debt, not an oversight).

ANCESTOR, TERM BY TERM: the published probe `src/probe/S1015.py`
(commutant_present, ladder [2,2]/[2,3,2]/[2,3,3,2]); ancestors T26.7/T29/T31.
GENERATED BY `gen_T263.py` — DO NOT EDIT BY HAND (rule 10).
-/

namespace VGLean.T263

open Matrix

/- ----- (d=2, m=1): dims (1, 0, 1), ladder=2 ----- -/

def v21_T1 : Fin 3 → ℚ := ![2, -1, -1]
theorem sum21_T1 : ∑ k, v21_T1 k = 0 := by
  simp only [v21_T1, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

def v21_STs0 : Fin 3 → ℚ := ![0, 1, -1]
theorem sum21_STs0 : ∑ k, v21_STs0 k = 0 := by
  simp only [v21_STs0, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

/-- (b) The d block vectors (last coordinate dropped) form a basis of V iff det != 0. -/
def M21 : Matrix (Fin 2) (Fin 2) ℚ :=
  !![2, -1; 0, 1]

theorem det21 : M21.det = 2 := by
  simp [M21, Matrix.det_fin_two] <;> norm_num

theorem indep21 : M21.det ≠ 0 := by rw [det21]; norm_num

/- (c) block dimensions = (1, m-1, d-m); (d) ladder = number of non-empty blocks. -/
theorem ladder21 :
    (1, 0, 1) = (1, 1 - 1, 2 - 1) ∧ 2 = 2 := by decide

/- ----- (d=2, m=2): dims (1, 1, 0), ladder=2 ----- -/

def v22_T1 : Fin 3 → ℚ := ![1, 1, -2]
theorem sum22_T1 : ∑ k, v22_T1 k = 0 := by
  simp only [v22_T1, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

def v22_STt0 : Fin 3 → ℚ := ![1, -1, 0]
theorem sum22_STt0 : ∑ k, v22_STt0 k = 0 := by
  simp only [v22_STt0, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

/-- (b) The d block vectors (last coordinate dropped) form a basis of V iff det != 0. -/
def M22 : Matrix (Fin 2) (Fin 2) ℚ :=
  !![1, 1; 1, -1]

theorem det22 : M22.det = -2 := by
  simp [M22, Matrix.det_fin_two] <;> norm_num

theorem indep22 : M22.det ≠ 0 := by rw [det22]; norm_num

/- (c) block dimensions = (1, m-1, d-m); (d) ladder = number of non-empty blocks. -/
theorem ladder22 :
    (1, 1, 0) = (1, 2 - 1, 2 - 2) ∧ 2 = 2 := by decide

/- ----- (d=3, m=1): dims (1, 0, 2), ladder=2 ----- -/

def v31_T1 : Fin 4 → ℚ := ![3, -1, -1, -1]
theorem sum31_T1 : ∑ k, v31_T1 k = 0 := by
  simp only [v31_T1, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

def v31_STs0 : Fin 4 → ℚ := ![0, 1, -1, 0]
theorem sum31_STs0 : ∑ k, v31_STs0 k = 0 := by
  simp only [v31_STs0, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

def v31_STs1 : Fin 4 → ℚ := ![0, 0, 1, -1]
theorem sum31_STs1 : ∑ k, v31_STs1 k = 0 := by
  simp only [v31_STs1, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

/-- (b) The d block vectors (last coordinate dropped) form a basis of V iff det != 0. -/
def M31 : Matrix (Fin 3) (Fin 3) ℚ :=
  !![3, -1, -1; 0, 1, -1; 0, 0, 1]

theorem det31 : M31.det = 3 := by
  simp [M31, Matrix.det_fin_three] <;> norm_num

theorem indep31 : M31.det ≠ 0 := by rw [det31]; norm_num

/- (c) block dimensions = (1, m-1, d-m); (d) ladder = number of non-empty blocks. -/
theorem ladder31 :
    (1, 0, 2) = (1, 1 - 1, 3 - 1) ∧ 2 = 2 := by decide

/- ----- (d=3, m=2): dims (1, 1, 1), ladder=3 ----- -/

def v32_T1 : Fin 4 → ℚ := ![2, 2, -2, -2]
theorem sum32_T1 : ∑ k, v32_T1 k = 0 := by
  simp only [v32_T1, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

def v32_STt0 : Fin 4 → ℚ := ![1, -1, 0, 0]
theorem sum32_STt0 : ∑ k, v32_STt0 k = 0 := by
  simp only [v32_STt0, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

def v32_STs0 : Fin 4 → ℚ := ![0, 0, 1, -1]
theorem sum32_STs0 : ∑ k, v32_STs0 k = 0 := by
  simp only [v32_STs0, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

/-- (b) The d block vectors (last coordinate dropped) form a basis of V iff det != 0. -/
def M32 : Matrix (Fin 3) (Fin 3) ℚ :=
  !![2, 2, -2; 1, -1, 0; 0, 0, 1]

theorem det32 : M32.det = -4 := by
  simp [M32, Matrix.det_fin_three] <;> norm_num

theorem indep32 : M32.det ≠ 0 := by rw [det32]; norm_num

/- (c) block dimensions = (1, m-1, d-m); (d) ladder = number of non-empty blocks. -/
theorem ladder32 :
    (1, 1, 1) = (1, 2 - 1, 3 - 2) ∧ 3 = 3 := by decide

/- ----- (d=3, m=3): dims (1, 2, 0), ladder=2 ----- -/

def v33_T1 : Fin 4 → ℚ := ![1, 1, 1, -3]
theorem sum33_T1 : ∑ k, v33_T1 k = 0 := by
  simp only [v33_T1, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

def v33_STt0 : Fin 4 → ℚ := ![1, -1, 0, 0]
theorem sum33_STt0 : ∑ k, v33_STt0 k = 0 := by
  simp only [v33_STt0, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

def v33_STt1 : Fin 4 → ℚ := ![0, 1, -1, 0]
theorem sum33_STt1 : ∑ k, v33_STt1 k = 0 := by
  simp only [v33_STt1, Fin.sum_univ_succ, Fin.sum_univ_zero, Matrix.cons_val_zero, Matrix.cons_val_succ] <;> norm_num

/-- (b) The d block vectors (last coordinate dropped) form a basis of V iff det != 0. -/
def M33 : Matrix (Fin 3) (Fin 3) ℚ :=
  !![1, 1, 1; 1, -1, 0; 0, 1, -1]

theorem det33 : M33.det = 3 := by
  simp [M33, Matrix.det_fin_three] <;> norm_num

theorem indep33 : M33.det ≠ 0 := by rw [det33]; norm_num

/- (c) block dimensions = (1, m-1, d-m); (d) ladder = number of non-empty blocks. -/
theorem ladder33 :
    (1, 2, 0) = (1, 3 - 1, 3 - 3) ∧ 2 = 2 := by decide

end VGLean.T263

/-! ## Axiom hygiene: EVERY theorem is stamped; the stamp is the exact triple OR A SUBSET. -/

/-- info: 'VGLean.T263.sum21_T1' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum21_T1
/-- info: 'VGLean.T263.sum21_STs0' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum21_STs0
/-- info: 'VGLean.T263.det21' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.det21
/-- info: 'VGLean.T263.indep21' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.indep21
/-- info: 'VGLean.T263.ladder21' does not depend on any axioms -/
#guard_msgs in
#print axioms VGLean.T263.ladder21
/-- info: 'VGLean.T263.sum22_T1' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum22_T1
/-- info: 'VGLean.T263.sum22_STt0' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum22_STt0
/-- info: 'VGLean.T263.det22' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.det22
/-- info: 'VGLean.T263.indep22' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.indep22
/-- info: 'VGLean.T263.ladder22' does not depend on any axioms -/
#guard_msgs in
#print axioms VGLean.T263.ladder22
/-- info: 'VGLean.T263.sum31_T1' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum31_T1
/-- info: 'VGLean.T263.sum31_STs0' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum31_STs0
/-- info: 'VGLean.T263.sum31_STs1' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum31_STs1
/-- info: 'VGLean.T263.det31' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.det31
/-- info: 'VGLean.T263.indep31' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.indep31
/-- info: 'VGLean.T263.ladder31' does not depend on any axioms -/
#guard_msgs in
#print axioms VGLean.T263.ladder31
/-- info: 'VGLean.T263.sum32_T1' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum32_T1
/-- info: 'VGLean.T263.sum32_STt0' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum32_STt0
/-- info: 'VGLean.T263.sum32_STs0' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum32_STs0
/-- info: 'VGLean.T263.det32' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.det32
/-- info: 'VGLean.T263.indep32' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.indep32
/-- info: 'VGLean.T263.ladder32' does not depend on any axioms -/
#guard_msgs in
#print axioms VGLean.T263.ladder32
/-- info: 'VGLean.T263.sum33_T1' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum33_T1
/-- info: 'VGLean.T263.sum33_STt0' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum33_STt0
/-- info: 'VGLean.T263.sum33_STt1' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.sum33_STt1
/-- info: 'VGLean.T263.det33' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.det33
/-- info: 'VGLean.T263.indep33' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in
#print axioms VGLean.T263.indep33
/-- info: 'VGLean.T263.ladder33' does not depend on any axioms -/
#guard_msgs in
#print axioms VGLean.T263.ladder33
