import Mathlib.Tactic

set_option linter.style.header false

/-!
# DIM: exact-integer / Layer-1 · T28 — COUNTING THE CLASSES OF iε-PRESCRIPTIONS

WHAT IS PROVED HERE (literally, with no wider wording):
for signatures (p,q) at L=4 — (a) the number of null modes of the Box; (b) the map
`ε ↦ label vector` SEPARATES all 2^q prescriptions (hence C(q)=2^q); (c) the net sum
of labels `D_net(ε)` equals 0 for EVERY ε; (d) the count of modes separating a pair.

WHY (b) IS NOT A TAUTOLOGY: `|{±1}^q| = 2^q` is true BY TYPING and is no witness at
all. The content of T28 is that the LATTICE could have GLUED prescriptions together
— and did not. So what is proved is SEPARATION: for each pair ε≠ε' a WITNESS null
mode with differing labels is exhibited. The witness is a hint from Python; Lean
verifies it FROM THE DEFINITIONS (`isNull` + label inequality), not as a literal.

SCOPE L in {3,4} — AN INHERITED BOUND, NOT A NEW ONE (address: S1073):
the table `2−2cos(2πk/L)` is integral exactly for L in {3,4} (for L=5 it is `(5±√5)/2`).
Here it is INTEGRAL by construction — the generator asserts `is_Integer` and fails otherwise.
This is NOT a fresh restriction of T28: the same `int(simplify(...))` lives in 9 ancestor probes.

ANCESTOR, TERM BY TERM: the published probe `src/probe/S1007.py` (tables T1/T2).
Every number below comes from ITS run, not "after the manner of" it.

GENERATED BY `lean/VGLean/gen_T28.py` — DO NOT EDIT BY HAND (rule 10).
-/

namespace VGLean.T28

/-- `2 − 2cos(2πk/4)` — exact INTEGER values (not truncation: at L=4 they are integers). -/
def term : Fin 4 → Int
  | 0 => 0
  | 1 => 2
  | 2 => 4
  | 3 => 2

/-- Sign of `sin(2πk/4)` in {−1,0,+1}; 0 = a MUTE axis (the mode does not see it). -/
def ssign : Fin 4 → Int
  | 0 => 0
  | 1 => 1
  | 2 => 0
  | 3 => -1

/- ----------- signature (4,0): q=0, 4 axes ----------- -/

abbrev K40 := Fin 4 × Fin 4 × Fin 4 × Fin 4

/-- Null mode: Sum(space) − Sum(time) = 0. -/
def isNull40 (k : K40) : Bool :=
  (term k.1 + term k.2.1 + term k.2.2.1 + term k.2.2.2) == 0

def nullCount40 : Nat := (Finset.univ.filter (fun k : K40 => isNull40 k)).card

set_option maxRecDepth 100000 in  -- elaborator budget, NOT a constant of the statement
theorem nullCount40_eq : nullCount40 = 1 := by decide


/- ----------- signature (3,1): q=1, 4 axes ----------- -/

abbrev K31 := Fin 4 × Fin 4 × Fin 4 × Fin 4

/-- Null mode: Sum(space) − Sum(time) = 0. -/
def isNull31 (k : K31) : Bool :=
  (term k.1 + term k.2.1 + term k.2.2.1)
    - (term k.2.2.2) == 0

def nullCount31 : Nat := (Finset.univ.filter (fun k : K31 => isNull31 k)).card

set_option maxRecDepth 100000 in  -- elaborator budget, NOT a constant of the statement
theorem nullCount31_eq : nullCount31 = 28 := by decide

/-- Label of a null mode under the prescription ε (ACTIVE axes only, `ssign ≠ 0`). -/
def label31 (e0 : Int) (k : K31) : Int :=
  let t := e0 * ssign k.2.2.2
  if t == 0 then 0 else if t > 0 then 1 else -1

def dnet31 (e0 : Int) : Int :=
  (Finset.univ.filter (fun k : K31 => isNull31 k)).sum (label31 e0)

set_option maxRecDepth 100000 in
theorem dnet31_p : dnet31 (1) = 0 := by decide

set_option maxRecDepth 100000 in
theorem dnet31_m : dnet31 (-1) = 0 := by decide

/- SEPARATION: for EVERY pair ε≠ε' a witness null mode with differing labels.
   Together: all 2^q label vectors are pairwise distinct, hence C(1) = 2. -/

/-- witness: null mode `(0, 0, 1, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist31_p_m :
    isNull31 (0, 0, 1, 1) = true ∧
      label31 (1) (0, 0, 1, 1)
        ≠ label31 (-1) (0, 0, 1, 1) := by decide

def hamCount31_p_m : Nat :=
  (Finset.univ.filter (fun k : K31 => isNull31 k &&
    label31 (1) k != label31 (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham31_p_m : hamCount31_p_m = 12 := by decide


/- ----------- signature (2,2): q=2, 4 axes ----------- -/

abbrev K22 := Fin 4 × Fin 4 × Fin 4 × Fin 4

/-- Null mode: Sum(space) − Sum(time) = 0. -/
def isNull22 (k : K22) : Bool :=
  (term k.1 + term k.2.1)
    - (term k.2.2.1 + term k.2.2.2) == 0

def nullCount22 : Nat := (Finset.univ.filter (fun k : K22 => isNull22 k)).card

set_option maxRecDepth 100000 in  -- elaborator budget, NOT a constant of the statement
theorem nullCount22_eq : nullCount22 = 70 := by decide

/-- Label of a null mode under the prescription ε (ACTIVE axes only, `ssign ≠ 0`). -/
def label22 (e0 : Int) (e1 : Int) (k : K22) : Int :=
  let t := e0 * ssign k.2.2.1 + e1 * ssign k.2.2.2
  if t == 0 then 0 else if t > 0 then 1 else -1

def dnet22 (e0 : Int) (e1 : Int) : Int :=
  (Finset.univ.filter (fun k : K22 => isNull22 k)).sum (label22 e0 e1)

set_option maxRecDepth 100000 in
theorem dnet22_pp : dnet22 (1) (1) = 0 := by decide

set_option maxRecDepth 100000 in
theorem dnet22_pm : dnet22 (1) (-1) = 0 := by decide

set_option maxRecDepth 100000 in
theorem dnet22_mp : dnet22 (-1) (1) = 0 := by decide

set_option maxRecDepth 100000 in
theorem dnet22_mm : dnet22 (-1) (-1) = 0 := by decide

/- SEPARATION: for EVERY pair ε≠ε' a witness null mode with differing labels.
   Together: all 2^q label vectors are pairwise distinct, hence C(2) = 4. -/

/-- witness: null mode `(0, 1, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist22_pp_pm :
    isNull22 (0, 1, 0, 1) = true ∧
      label22 (1) (1) (0, 1, 0, 1)
        ≠ label22 (1) (-1) (0, 1, 0, 1) := by decide

def hamCount22_pp_pm : Nat :=
  (Finset.univ.filter (fun k : K22 => isNull22 k &&
    label22 (1) (1) k != label22 (1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham22_pp_pm : hamCount22_pp_pm = 40 := by decide

/-- witness: null mode `(0, 1, 1, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist22_pp_mp :
    isNull22 (0, 1, 1, 0) = true ∧
      label22 (1) (1) (0, 1, 1, 0)
        ≠ label22 (-1) (1) (0, 1, 1, 0) := by decide

def hamCount22_pp_mp : Nat :=
  (Finset.univ.filter (fun k : K22 => isNull22 k &&
    label22 (1) (1) k != label22 (-1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham22_pp_mp : hamCount22_pp_mp = 40 := by decide

/-- witness: null mode `(0, 1, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist22_pp_mm :
    isNull22 (0, 1, 0, 1) = true ∧
      label22 (1) (1) (0, 1, 0, 1)
        ≠ label22 (-1) (-1) (0, 1, 0, 1) := by decide

def hamCount22_pp_mm : Nat :=
  (Finset.univ.filter (fun k : K22 => isNull22 k &&
    label22 (1) (1) k != label22 (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham22_pp_mm : hamCount22_pp_mm = 44 := by decide

/-- witness: null mode `(0, 1, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist22_pm_mp :
    isNull22 (0, 1, 0, 1) = true ∧
      label22 (1) (-1) (0, 1, 0, 1)
        ≠ label22 (-1) (1) (0, 1, 0, 1) := by decide

def hamCount22_pm_mp : Nat :=
  (Finset.univ.filter (fun k : K22 => isNull22 k &&
    label22 (1) (-1) k != label22 (-1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham22_pm_mp : hamCount22_pm_mp = 44 := by decide

/-- witness: null mode `(0, 1, 1, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist22_pm_mm :
    isNull22 (0, 1, 1, 0) = true ∧
      label22 (1) (-1) (0, 1, 1, 0)
        ≠ label22 (-1) (-1) (0, 1, 1, 0) := by decide

def hamCount22_pm_mm : Nat :=
  (Finset.univ.filter (fun k : K22 => isNull22 k &&
    label22 (1) (-1) k != label22 (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham22_pm_mm : hamCount22_pm_mm = 40 := by decide

/-- witness: null mode `(0, 1, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist22_mp_mm :
    isNull22 (0, 1, 0, 1) = true ∧
      label22 (-1) (1) (0, 1, 0, 1)
        ≠ label22 (-1) (-1) (0, 1, 0, 1) := by decide

def hamCount22_mp_mm : Nat :=
  (Finset.univ.filter (fun k : K22 => isNull22 k &&
    label22 (-1) (1) k != label22 (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham22_mp_mm : hamCount22_mp_mm = 40 := by decide


/- ----------- signature (3,3): q=3, 6 axes ----------- -/

abbrev K33 := Fin 4 × Fin 4 × Fin 4 × Fin 4 × Fin 4 × Fin 4

/-- Null mode: Sum(space) − Sum(time) = 0. -/
def isNull33 (k : K33) : Bool :=
  (term k.1 + term k.2.1 + term k.2.2.1)
    - (term k.2.2.2.1 + term k.2.2.2.2.1 + term k.2.2.2.2.2) == 0

def nullCount33 : Nat := (Finset.univ.filter (fun k : K33 => isNull33 k)).card

set_option maxRecDepth 100000 in  -- elaborator budget, NOT a constant of the statement
theorem nullCount33_eq : nullCount33 = 924 := by decide

/-- Label of a null mode under the prescription ε (ACTIVE axes only, `ssign ≠ 0`). -/
def label33 (e0 : Int) (e1 : Int) (e2 : Int) (k : K33) : Int :=
  let t := e0 * ssign k.2.2.2.1 + e1 * ssign k.2.2.2.2.1 + e2 * ssign k.2.2.2.2.2
  if t == 0 then 0 else if t > 0 then 1 else -1

def dnet33 (e0 : Int) (e1 : Int) (e2 : Int) : Int :=
  (Finset.univ.filter (fun k : K33 => isNull33 k)).sum (label33 e0 e1 e2)

set_option maxRecDepth 100000 in
theorem dnet33_ppp : dnet33 (1) (1) (1) = 0 := by decide

set_option maxRecDepth 100000 in
theorem dnet33_ppm : dnet33 (1) (1) (-1) = 0 := by decide

set_option maxRecDepth 100000 in
theorem dnet33_pmp : dnet33 (1) (-1) (1) = 0 := by decide

set_option maxRecDepth 100000 in
theorem dnet33_pmm : dnet33 (1) (-1) (-1) = 0 := by decide

set_option maxRecDepth 100000 in
theorem dnet33_mpp : dnet33 (-1) (1) (1) = 0 := by decide

set_option maxRecDepth 100000 in
theorem dnet33_mpm : dnet33 (-1) (1) (-1) = 0 := by decide

set_option maxRecDepth 100000 in
theorem dnet33_mmp : dnet33 (-1) (-1) (1) = 0 := by decide

set_option maxRecDepth 100000 in
theorem dnet33_mmm : dnet33 (-1) (-1) (-1) = 0 := by decide

/- SEPARATION: for EVERY pair ε≠ε' a witness null mode with differing labels.
   Together: all 2^q label vectors are pairwise distinct, hence C(3) = 8. -/

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppp_ppm :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (1) (1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (1) (1) (-1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_ppp_ppm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (1) k != label33 (1) (1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppp_ppm : hamCount33_ppp_ppm = 424 := by decide

/-- witness: null mode `(0, 0, 1, 0, 1, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppp_pmp :
    isNull33 (0, 0, 1, 0, 1, 0) = true ∧
      label33 (1) (1) (1) (0, 0, 1, 0, 1, 0)
        ≠ label33 (1) (-1) (1) (0, 0, 1, 0, 1, 0) := by decide

def hamCount33_ppp_pmp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (1) k != label33 (1) (-1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppp_pmp : hamCount33_ppp_pmp = 424 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppp_pmm :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (1) (1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (1) (-1) (-1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_ppp_pmm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (1) k != label33 (1) (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppp_pmm : hamCount33_ppp_pmm = 588 := by decide

/-- witness: null mode `(0, 0, 1, 1, 0, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppp_mpp :
    isNull33 (0, 0, 1, 1, 0, 0) = true ∧
      label33 (1) (1) (1) (0, 0, 1, 1, 0, 0)
        ≠ label33 (-1) (1) (1) (0, 0, 1, 1, 0, 0) := by decide

def hamCount33_ppp_mpp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (1) k != label33 (-1) (1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppp_mpp : hamCount33_ppp_mpp = 424 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppp_mpm :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (1) (1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (1) (-1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_ppp_mpm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (1) k != label33 (-1) (1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppp_mpm : hamCount33_ppp_mpm = 588 := by decide

/-- witness: null mode `(0, 0, 1, 0, 1, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppp_mmp :
    isNull33 (0, 0, 1, 0, 1, 0) = true ∧
      label33 (1) (1) (1) (0, 0, 1, 0, 1, 0)
        ≠ label33 (-1) (-1) (1) (0, 0, 1, 0, 1, 0) := by decide

def hamCount33_ppp_mmp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (1) k != label33 (-1) (-1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppp_mmp : hamCount33_ppp_mmp = 588 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppp_mmm :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (1) (1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (-1) (-1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_ppp_mmm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (1) k != label33 (-1) (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppp_mmm : hamCount33_ppp_mmm = 652 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppm_pmp :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (1) (-1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (1) (-1) (1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_ppm_pmp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (-1) k != label33 (1) (-1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppm_pmp : hamCount33_ppm_pmp = 588 := by decide

/-- witness: null mode `(0, 0, 1, 0, 1, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppm_pmm :
    isNull33 (0, 0, 1, 0, 1, 0) = true ∧
      label33 (1) (1) (-1) (0, 0, 1, 0, 1, 0)
        ≠ label33 (1) (-1) (-1) (0, 0, 1, 0, 1, 0) := by decide

def hamCount33_ppm_pmm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (-1) k != label33 (1) (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppm_pmm : hamCount33_ppm_pmm = 424 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppm_mpp :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (1) (-1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (1) (1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_ppm_mpp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (-1) k != label33 (-1) (1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppm_mpp : hamCount33_ppm_mpp = 588 := by decide

/-- witness: null mode `(0, 0, 1, 1, 0, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppm_mpm :
    isNull33 (0, 0, 1, 1, 0, 0) = true ∧
      label33 (1) (1) (-1) (0, 0, 1, 1, 0, 0)
        ≠ label33 (-1) (1) (-1) (0, 0, 1, 1, 0, 0) := by decide

def hamCount33_ppm_mpm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (-1) k != label33 (-1) (1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppm_mpm : hamCount33_ppm_mpm = 424 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppm_mmp :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (1) (-1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (-1) (1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_ppm_mmp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (-1) k != label33 (-1) (-1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppm_mmp : hamCount33_ppm_mmp = 652 := by decide

/-- witness: null mode `(0, 0, 1, 0, 1, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_ppm_mmm :
    isNull33 (0, 0, 1, 0, 1, 0) = true ∧
      label33 (1) (1) (-1) (0, 0, 1, 0, 1, 0)
        ≠ label33 (-1) (-1) (-1) (0, 0, 1, 0, 1, 0) := by decide

def hamCount33_ppm_mmm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (1) (-1) k != label33 (-1) (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_ppm_mmm : hamCount33_ppm_mmm = 588 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_pmp_pmm :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (-1) (1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (1) (-1) (-1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_pmp_pmm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (-1) (1) k != label33 (1) (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_pmp_pmm : hamCount33_pmp_pmm = 424 := by decide

/-- witness: null mode `(0, 0, 1, 0, 1, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_pmp_mpp :
    isNull33 (0, 0, 1, 0, 1, 0) = true ∧
      label33 (1) (-1) (1) (0, 0, 1, 0, 1, 0)
        ≠ label33 (-1) (1) (1) (0, 0, 1, 0, 1, 0) := by decide

def hamCount33_pmp_mpp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (-1) (1) k != label33 (-1) (1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_pmp_mpp : hamCount33_pmp_mpp = 588 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_pmp_mpm :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (-1) (1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (1) (-1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_pmp_mpm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (-1) (1) k != label33 (-1) (1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_pmp_mpm : hamCount33_pmp_mpm = 652 := by decide

/-- witness: null mode `(0, 0, 1, 1, 0, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_pmp_mmp :
    isNull33 (0, 0, 1, 1, 0, 0) = true ∧
      label33 (1) (-1) (1) (0, 0, 1, 1, 0, 0)
        ≠ label33 (-1) (-1) (1) (0, 0, 1, 1, 0, 0) := by decide

def hamCount33_pmp_mmp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (-1) (1) k != label33 (-1) (-1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_pmp_mmp : hamCount33_pmp_mmp = 424 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_pmp_mmm :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (-1) (1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (-1) (-1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_pmp_mmm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (-1) (1) k != label33 (-1) (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_pmp_mmm : hamCount33_pmp_mmm = 588 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_pmm_mpp :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (-1) (-1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (1) (1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_pmm_mpp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (-1) (-1) k != label33 (-1) (1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_pmm_mpp : hamCount33_pmm_mpp = 652 := by decide

/-- witness: null mode `(0, 0, 1, 0, 1, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_pmm_mpm :
    isNull33 (0, 0, 1, 0, 1, 0) = true ∧
      label33 (1) (-1) (-1) (0, 0, 1, 0, 1, 0)
        ≠ label33 (-1) (1) (-1) (0, 0, 1, 0, 1, 0) := by decide

def hamCount33_pmm_mpm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (-1) (-1) k != label33 (-1) (1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_pmm_mpm : hamCount33_pmm_mpm = 588 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_pmm_mmp :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (1) (-1) (-1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (-1) (1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_pmm_mmp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (-1) (-1) k != label33 (-1) (-1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_pmm_mmp : hamCount33_pmm_mmp = 588 := by decide

/-- witness: null mode `(0, 0, 1, 1, 0, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_pmm_mmm :
    isNull33 (0, 0, 1, 1, 0, 0) = true ∧
      label33 (1) (-1) (-1) (0, 0, 1, 1, 0, 0)
        ≠ label33 (-1) (-1) (-1) (0, 0, 1, 1, 0, 0) := by decide

def hamCount33_pmm_mmm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (1) (-1) (-1) k != label33 (-1) (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_pmm_mmm : hamCount33_pmm_mmm = 424 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_mpp_mpm :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (-1) (1) (1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (1) (-1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_mpp_mpm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (-1) (1) (1) k != label33 (-1) (1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_mpp_mpm : hamCount33_mpp_mpm = 424 := by decide

/-- witness: null mode `(0, 0, 1, 0, 1, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_mpp_mmp :
    isNull33 (0, 0, 1, 0, 1, 0) = true ∧
      label33 (-1) (1) (1) (0, 0, 1, 0, 1, 0)
        ≠ label33 (-1) (-1) (1) (0, 0, 1, 0, 1, 0) := by decide

def hamCount33_mpp_mmp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (-1) (1) (1) k != label33 (-1) (-1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_mpp_mmp : hamCount33_mpp_mmp = 424 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_mpp_mmm :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (-1) (1) (1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (-1) (-1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_mpp_mmm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (-1) (1) (1) k != label33 (-1) (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_mpp_mmm : hamCount33_mpp_mmm = 588 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_mpm_mmp :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (-1) (1) (-1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (-1) (1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_mpm_mmp : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (-1) (1) (-1) k != label33 (-1) (-1) (1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_mpm_mmp : hamCount33_mpm_mmp = 588 := by decide

/-- witness: null mode `(0, 0, 1, 0, 1, 0)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_mpm_mmm :
    isNull33 (0, 0, 1, 0, 1, 0) = true ∧
      label33 (-1) (1) (-1) (0, 0, 1, 0, 1, 0)
        ≠ label33 (-1) (-1) (-1) (0, 0, 1, 0, 1, 0) := by decide

def hamCount33_mpm_mmm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (-1) (1) (-1) k != label33 (-1) (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_mpm_mmm : hamCount33_mpm_mmm = 424 := by decide

/-- witness: null mode `(0, 0, 1, 0, 0, 1)`; labels differ, so the prescriptions are SEPARATED. -/
theorem dist33_mmp_mmm :
    isNull33 (0, 0, 1, 0, 0, 1) = true ∧
      label33 (-1) (-1) (1) (0, 0, 1, 0, 0, 1)
        ≠ label33 (-1) (-1) (-1) (0, 0, 1, 0, 0, 1) := by decide

def hamCount33_mmp_mmm : Nat :=
  (Finset.univ.filter (fun k : K33 => isNull33 k &&
    label33 (-1) (-1) (1) k != label33 (-1) (-1) (-1) k)).card

set_option maxRecDepth 100000 in
theorem ham33_mmp_mmm : hamCount33_mmp_mmm = 424 := by decide


end VGLean.T28

/-! ## Axiom hygiene: EVERY theorem is stamped, and the stamp is the exact
triple OR A SUBSET of it ("narrower" is meant strictly as a subset —
`native_decide` yields a SHORTER but DISJOINT list). The expectations are taken
FROM THE BUILD LOG (2nd pass `gen_T28.py --guard`), not from memory. -/

/-- info: 'VGLean.T28.nullCount40_eq' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.nullCount40_eq
/-- info: 'VGLean.T28.nullCount31_eq' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.nullCount31_eq
/-- info: 'VGLean.T28.dnet31_p' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet31_p
/-- info: 'VGLean.T28.dnet31_m' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet31_m
/-- info: 'VGLean.T28.dist31_p_m' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist31_p_m
/-- info: 'VGLean.T28.ham31_p_m' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham31_p_m
/-- info: 'VGLean.T28.nullCount22_eq' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.nullCount22_eq
/-- info: 'VGLean.T28.dnet22_pp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet22_pp
/-- info: 'VGLean.T28.dnet22_pm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet22_pm
/-- info: 'VGLean.T28.dnet22_mp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet22_mp
/-- info: 'VGLean.T28.dnet22_mm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet22_mm
/-- info: 'VGLean.T28.dist22_pp_pm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist22_pp_pm
/-- info: 'VGLean.T28.ham22_pp_pm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham22_pp_pm
/-- info: 'VGLean.T28.dist22_pp_mp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist22_pp_mp
/-- info: 'VGLean.T28.ham22_pp_mp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham22_pp_mp
/-- info: 'VGLean.T28.dist22_pp_mm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist22_pp_mm
/-- info: 'VGLean.T28.ham22_pp_mm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham22_pp_mm
/-- info: 'VGLean.T28.dist22_pm_mp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist22_pm_mp
/-- info: 'VGLean.T28.ham22_pm_mp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham22_pm_mp
/-- info: 'VGLean.T28.dist22_pm_mm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist22_pm_mm
/-- info: 'VGLean.T28.ham22_pm_mm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham22_pm_mm
/-- info: 'VGLean.T28.dist22_mp_mm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist22_mp_mm
/-- info: 'VGLean.T28.ham22_mp_mm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham22_mp_mm
/-- info: 'VGLean.T28.nullCount33_eq' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.nullCount33_eq
/-- info: 'VGLean.T28.dnet33_ppp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet33_ppp
/-- info: 'VGLean.T28.dnet33_ppm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet33_ppm
/-- info: 'VGLean.T28.dnet33_pmp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet33_pmp
/-- info: 'VGLean.T28.dnet33_pmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet33_pmm
/-- info: 'VGLean.T28.dnet33_mpp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet33_mpp
/-- info: 'VGLean.T28.dnet33_mpm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet33_mpm
/-- info: 'VGLean.T28.dnet33_mmp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet33_mmp
/-- info: 'VGLean.T28.dnet33_mmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.dnet33_mmm
/-- info: 'VGLean.T28.dist33_ppp_ppm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppp_ppm
/-- info: 'VGLean.T28.ham33_ppp_ppm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppp_ppm
/-- info: 'VGLean.T28.dist33_ppp_pmp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppp_pmp
/-- info: 'VGLean.T28.ham33_ppp_pmp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppp_pmp
/-- info: 'VGLean.T28.dist33_ppp_pmm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppp_pmm
/-- info: 'VGLean.T28.ham33_ppp_pmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppp_pmm
/-- info: 'VGLean.T28.dist33_ppp_mpp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppp_mpp
/-- info: 'VGLean.T28.ham33_ppp_mpp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppp_mpp
/-- info: 'VGLean.T28.dist33_ppp_mpm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppp_mpm
/-- info: 'VGLean.T28.ham33_ppp_mpm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppp_mpm
/-- info: 'VGLean.T28.dist33_ppp_mmp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppp_mmp
/-- info: 'VGLean.T28.ham33_ppp_mmp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppp_mmp
/-- info: 'VGLean.T28.dist33_ppp_mmm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppp_mmm
/-- info: 'VGLean.T28.ham33_ppp_mmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppp_mmm
/-- info: 'VGLean.T28.dist33_ppm_pmp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppm_pmp
/-- info: 'VGLean.T28.ham33_ppm_pmp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppm_pmp
/-- info: 'VGLean.T28.dist33_ppm_pmm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppm_pmm
/-- info: 'VGLean.T28.ham33_ppm_pmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppm_pmm
/-- info: 'VGLean.T28.dist33_ppm_mpp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppm_mpp
/-- info: 'VGLean.T28.ham33_ppm_mpp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppm_mpp
/-- info: 'VGLean.T28.dist33_ppm_mpm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppm_mpm
/-- info: 'VGLean.T28.ham33_ppm_mpm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppm_mpm
/-- info: 'VGLean.T28.dist33_ppm_mmp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppm_mmp
/-- info: 'VGLean.T28.ham33_ppm_mmp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppm_mmp
/-- info: 'VGLean.T28.dist33_ppm_mmm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_ppm_mmm
/-- info: 'VGLean.T28.ham33_ppm_mmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_ppm_mmm
/-- info: 'VGLean.T28.dist33_pmp_pmm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_pmp_pmm
/-- info: 'VGLean.T28.ham33_pmp_pmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_pmp_pmm
/-- info: 'VGLean.T28.dist33_pmp_mpp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_pmp_mpp
/-- info: 'VGLean.T28.ham33_pmp_mpp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_pmp_mpp
/-- info: 'VGLean.T28.dist33_pmp_mpm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_pmp_mpm
/-- info: 'VGLean.T28.ham33_pmp_mpm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_pmp_mpm
/-- info: 'VGLean.T28.dist33_pmp_mmp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_pmp_mmp
/-- info: 'VGLean.T28.ham33_pmp_mmp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_pmp_mmp
/-- info: 'VGLean.T28.dist33_pmp_mmm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_pmp_mmm
/-- info: 'VGLean.T28.ham33_pmp_mmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_pmp_mmm
/-- info: 'VGLean.T28.dist33_pmm_mpp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_pmm_mpp
/-- info: 'VGLean.T28.ham33_pmm_mpp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_pmm_mpp
/-- info: 'VGLean.T28.dist33_pmm_mpm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_pmm_mpm
/-- info: 'VGLean.T28.ham33_pmm_mpm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_pmm_mpm
/-- info: 'VGLean.T28.dist33_pmm_mmp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_pmm_mmp
/-- info: 'VGLean.T28.ham33_pmm_mmp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_pmm_mmp
/-- info: 'VGLean.T28.dist33_pmm_mmm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_pmm_mmm
/-- info: 'VGLean.T28.ham33_pmm_mmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_pmm_mmm
/-- info: 'VGLean.T28.dist33_mpp_mpm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_mpp_mpm
/-- info: 'VGLean.T28.ham33_mpp_mpm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_mpp_mpm
/-- info: 'VGLean.T28.dist33_mpp_mmp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_mpp_mmp
/-- info: 'VGLean.T28.ham33_mpp_mmp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_mpp_mmp
/-- info: 'VGLean.T28.dist33_mpp_mmm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_mpp_mmm
/-- info: 'VGLean.T28.ham33_mpp_mmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_mpp_mmm
/-- info: 'VGLean.T28.dist33_mpm_mmp' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_mpm_mmp
/-- info: 'VGLean.T28.ham33_mpm_mmp' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_mpm_mmp
/-- info: 'VGLean.T28.dist33_mpm_mmm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_mpm_mmm
/-- info: 'VGLean.T28.ham33_mpm_mmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_mpm_mmm
/-- info: 'VGLean.T28.dist33_mmp_mmm' depends on axioms: [propext] -/
#guard_msgs in

#print axioms VGLean.T28.dist33_mmp_mmm
/-- info: 'VGLean.T28.ham33_mmp_mmm' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in

#print axioms VGLean.T28.ham33_mmp_mmm
